### ISSUE TITLE
cc 1.0.87 cause build error with warning

### ISSUE THREAD

**Issue by sehz** [rust-lang/cc-rs#971] opened 2024-02-24 06:09 UTC
```
warning: zstd-sys@2.0.9+zstd.1.5.5: error: UnknownOperatingSystem
warning: zstd-sys@2.0.9+zstd.1.5.5: running: "/home/runner/work/my-project/build-scripts/x86_64-linux-musl-zig-cc" "--version"
warning: zstd-sys@2.0.9+zstd.1.5.5: exit status: 0
```

**Comment by sehz** [comment] 2024-02-24 06:10
Suggest revert back changes to `1.0.83` which was stable

**Comment by NobodyXu** [comment] 2024-02-24 06:50
Duplicate of #970

**Comment by NobodyXu** [comment] 2024-02-24 06:51
> Suggest revert back changes to `1.0.83` which was stable

It's not a hard error, just debugging print of internal which might be useful on failure.

**Comment by sehz** [comment] 2024-02-24 18:01
It cause build failure:
```
warning: zstd-sys@2.0.9+zstd.1.5.5: ToolExecError: Command "/home/runner/work/myproject/build-scripts/x86_64-linux-musl-zig-cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-gdwarf-4" "-fno-omit-frame-pointer" "-m64" "--target=x86_64-unknown-linux-musl" "-I" "zstd/lib/" "-I" "zstd/lib/common" "-fvisibility=hidden" "-DZSTD_LIB_DEPRECATED=0" "-DXXH_PRIVATE_API=" "-DZSTDLIB_VISIBILITY=" "-DZSTDERRORLIB_VISIBILITY=" "-o" "/home/runner/work/myproject/target/x86_64-unknown-linux-musl/debug/build/zstd-sys-6de595e827a277a5/out/690f776bf7b37aeb-huf_decompress_amd64.o" "-c" "zstd/lib/decompress/huf_decompress_amd64.S" with args "x86_64-linux-musl-zig-cc" did not execute successfully (status code exit status: 1).

error: failed to run custom build command for `zstd-sys v2.0.9+zstd.1.5.5`
```

**Comment by NobodyXu** [comment] 2024-02-24 22:19
I think this is rhe same issue in #948 , which also has a tracking issue in upstream ziglang/zig#4911

@sehz I recommend you to use https://github.com/rust-cross/cargo-zigbuild , it has workarounds for common issues of zig.

**Closed** 2024-02-25 09:29 UTC
