### ISSUE TITLE
Generate `compile_commands.json` for clangd

### ISSUE THREAD

**Issue by HKalbasi** [rust-lang/cc-rs#691] opened 2022-06-30 17:35 UTC
There is a [json compilation database](https://clang.llvm.org/docs/JSONCompilationDatabase.html) format that c/c++ tools like clangd (lsp for c/c++, like rust-analyzer for rust) can use to understand c/c++ projects without knowing about the build system. Some build systems like `cmake` have first class support for it. It would be great to support an option for emitting it inside `build.rs`. There is a tool called `bear` that can proxy the calls to the compiler and emit that json but updating at each build without running a separate tool is even better.

**Comment by ldesgoui** [comment] 2022-07-01 22:54
Dupe of #497

**Closed** 2022-07-02 06:46 UTC
