### ISSUE TITLE
How to get a more friendly error message in cc?

### ISSUE THREAD

**Issue by mingerfan** [rust-lang/cc-rs#1260] opened 2024-11-02 15:19 UTC
I'm looking for a way to get more user-friendly error messages to help diagnose issues in my C/C++ code or the bridging code between Rust and C. How can I achieve this?

Here's a simple example of what I'm facing:

Suppose you have a C file intended for use in Rust. You would typically compile it in build.rs using the cc crate. If the C file is correct, everything works fine. However, in the example below, the error message is quite confusing.
![Image](https://github.com/user-attachments/assets/5897883a-b8d2-4d3e-8a70-aaee13a63879)
![Image](https://github.com/user-attachments/assets/7d2584e8-348a-41f6-b0f2-06d39664cdc7)

You can see that cc simply reports "error occurred" without providing further details. In contrast, compiling the same file with gcc highlights the specific error line.Is there a way to configure the cc crate to provide detailed gcc or msvc error messages when there are issues in my C/C++ code? How can I set this up?

**Comment by NobodyXu** [comment] 2024-11-03 01:09
Does you code call `Build::cargo_output(false)`?

That disables compiler stdout forwarding

**Comment by mingerfan** [comment] 2024-11-03 15:04
> Does you code call `Build::cargo_output(false)`?
> 
> That disables compiler stdout forwarding

No, I explicitly call cargo_output(true) in my build.rs;
![Image](https://github.com/user-attachments/assets/c7d7b668-b333-4424-9c1d-e133121d3760)

**Comment by madsmtm** [comment] 2024-11-03 18:59
Could you try to invoke the command that the commandline says that `cc` ran (the line with `error occurred: Command`)? Seems like `cc` is trying to invoke `cl.exe`, but you've only showed that `gcc` works

**Comment by mingerfan** [comment] 2024-11-04 08:36
> Could you try to invoke the command that the commandline says that `cc` ran (the line with `error occurred: Command`)? Seems like `cc` is trying to invoke `cl.exe`, but you've only showed that `gcc` works

When I run this code in linux, cargo shows gcc error message. 
![Image](https://github.com/user-attachments/assets/f408dfa5-2e73-41b3-8090-06ce4ba8d75f)
In windows(msvc), cargo doesn't.
![Image](https://github.com/user-attachments/assets/e40cafa4-0794-4eca-acee-d13b1e3a3666)

And msvc also reports error when I use it to compile the wrong c code(using command line). But the message is non-ASCII string.
![Image](https://github.com/user-attachments/assets/79b01f2e-8e86-41d1-97fc-0c39955f65b8)


I change toolchains to gcc, and it is ok in windows.
![Image](https://github.com/user-attachments/assets/f328fc2b-d90f-4917-9f47-3af242d58cdc)
![Image](https://github.com/user-attachments/assets/a22a9c34-f3db-4b70-9fb3-139e1d23612b)


So, is this because cargo warning or windows powershell doesn't support non-ASCII message?

**Comment by NobodyXu** [comment] 2024-11-04 09:19
Hmm, does cl.exe print error to stderr or stdout?

For stdout we just set it to inherit the stdin of build-script, so it should work fine.

For stderr forward, cc simply just write `cargo:warning={msg}\n`

https://docs.rs/cc/latest/src/cc/command_helpers.rs.html#239

There's line splitting, but it also flushes the stderr at the end, so not sure

**Comment by mingerfan** [comment] 2024-11-04 12:51
> Hmm, does cl.exe print error to stderr or stdout?
> 
> For stdout we just set it to inherit the stdin of build-script, so it should work fine.
> 
> For stderr forward, cc simply just write `cargo:warning={msg}\n`
> 
> https://docs.rs/cc/latest/src/cc/command_helpers.rs.html#239
> 
> There's line splitting, but it also flushes the stderr at the end, and I think rust stdlib deal with the encoding stuff, so it should be fine...

In my experiment, cl.exe prints error to stdout.
``` Shell
# cl.exe
E:\\programme\\vs2019\\software\\VC\\Tools\\MSVC\\14.41.34120\\bin\\HostX64\\x64\\cl.exe src/test.c > stdout.log 2> stderr.log

## stdout.log
test.c
src/test.c(3): error C2143: 语法错误: 缺少“;”(在“}”的前面)

## stderr.log
E:\\programme\\vs2019\\software\\VC\\Tools\\MSVC\\14.41.34120\\bin\\HostX64\\x64\\cl.exe : 用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.41.34123 版
所在位置 行:1 字符: 1
+ E:\\programme\\vs2019\\software\\VC\\Tools\\MSVC\\14.41.34120\\bin\\H ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (用于 x64 的 Micros...器 19.41.34123 版:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
版权所有(C) Microsoft Corporation。保留所有权利。
```
while gcc prints error to stderr
``` Shell
# gcc
gcc src/test.c > stdoutgcc.log 2> stderrgcc.log

## stdoutgcc.log          

## stderrgcc.log
gcc : src/test.c: In function 'main':
所在位置 行:1 字符: 1
+ gcc src/test.c > stdoutgcc.log 2> stderrgcc.log
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (src/test.c: In function 'main'::String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
src/test.c:2:13: error: expected ';' before '}' token
    2 |     return 0
      |             ^
      |             ;
    3 | }
      | ~  
```

**Comment by mingerfan** [comment] 2024-11-05 15:40
> Hmm maybe we need to forward stdout as well as stderr for the `cl.exe`

After my research, I found that there are two main difficulties in supporting error capture and output for MSVC.

Firstly, UTF-8 encoding support on Windows is an experimental feature that is not enabled by default (this seems to have been the case since Windows 10 and has persisted for quite some time). As a result, many users in non-English speaking countries use PowerShell or CMD programs that are not UTF-8 encoded. The MSVC output in these terminals is also not in UTF-8 format. This makes handling stdout and stderr using Rust's `String` very difficult. Here is an example:

```rust
let mut s = String::new();
if let Err(e) = child.stdout.take().unwrap().read_to_string(&mut s) {
    eprintln!("Failed to read child stdout: {}", e);
} else {
    eprintln!("child stdout: {}", s);
}
```
This works well for UTF-8 encoded terminals. However, in non-UTF-8 encoded terminals, it enters the else branch and fails to correctly output MSVC errors.

The second difficulty is that the forward_available function in command_helpers.rs currently only supports capturing and outputting stderr. In the settings, stdout seems to be either forwarded or discarded in most cases (depending on the .cargo_output(bool) setting). To capture the output, these codes need to be modified.

Capturing MSVC's stdout and outputting it in a similar manner to stderr seems to be quite challenging, so I feel that directly forwarding the output is a simpler choice.

However, the problem then becomes, why does forwarding not work effectively on Windows? This is a very strange issue.
Here is my experiment:
``` shell
PS C:\Users\xs\Desktop\test_cc> cargo build
   Compiling test_cc v0.1.0 (C:\Users\xs\Desktop\test_cc)
error: failed to run custom build command for `test_cc v0.1.0 (C:\Users\xs\Desktop\test_cc)`                                                                                                                                                                                         

Caused by:
  process didn't exit successfully: `C:\Users\xs\Desktop\test_cc\target\debug\build\test_cc-fd694f9983ca928f\build-script-build` (exit code: 1)
  --- stderr


  error occurred: Command "E:\\programme\\vs2019\\software\\VC\\Tools\\MSVC\\14.41.34120\\bin\\HostX64\\x64\\cl.exe" "-nologo" "-MD" "-Z7" "-Brepro" "-W4" "-Fo./2e40c9e35e9506f4-test.o" "-c" "src/test.c" with args cl.exe did not execute successfully (status code exit code: 2).

PS C:\Users\xs\Desktop\test_cc> chcp
活动代码页: 936

//  change encoding to utf-8
PS C:\Users\xs\Desktop\test_cc> chcp 65001
Active code page: 65001

PS C:\Users\xs\Desktop\test_cc> cargo build
   Compiling test_cc v0.1.0 (C:\Users\xs\Desktop\test_cc)
error: failed to run custom build command for `test_cc v0.1.0 (C:\Users\xs\Desktop\test_cc)`

Caused by:
  process didn't exit successfully: `C:\Users\xs\Desktop\test_cc\target\debug\build\test_cc-fd694f9983ca928f\build-script-build` (exit code: 1)
  --- stdout
  OPT_LEVEL = Some(0)
  TARGET = Some(x86_64-pc-windows-msvc)
  cargo:rerun-if-env-changed=VCINSTALLDIR
  VCINSTALLDIR = None
  cargo:rerun-if-env-changed=VSTEL_MSBuildProjectFullPath
 .....
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  cargo:rerun-if-env-changed=CC_ENABLE_DEBUG_OUTPUT
  **_test.c
  src/test.c(3): error C2143: syntax error: missing ';' before '}'_**

  --- stderr
  

  error occurred: Command "E:\\programme\\vs2019\\software\\VC\\Tools\\MSVC\\14.41.34120\\bin\\HostX64\\x64\\cl.exe" "-nologo" "-MD" "-Z7" "-Brepro" "-W4" "-Fo./2e40c9e35e9506f4-test.o" "-c" "src/test.c" with args cl.exe did not execute successfully (status code exit code: 2).
```

So, what happened?

**Comment by NobodyXu** [comment] 2024-11-05 21:24
So it works if it is under utf-8?

😨 cc @ChrisDenton do you have any idea why forwarding fail on Windows when not using utf-8?

**Comment by ChrisDenton** [comment] 2024-11-05 22:11
I've not looked into it yet but this is almost certainly a Cargo issue. Or at least has nothing to do with cc directly. I suspect you can reproduce the issue just by having a build script that prints non UTF-8 to stdout. It might not even be a Windows specific issue if it's only being encountered because `cl.exe` produces non-unicode output.

**Comment by ChrisDenton** [comment] 2024-11-05 22:59
I've opened a Cargo issue about this. Let's see what they say.

As I mentioned in that issue, it'd be good if cc-rs could convert the output of `cl.exe` so that it is output as UTF-8. I believe I wrote something similar for rustc but that was `link.exe`. I'm not sure if `cl.exe` uses the same code page (old tools with a long history have some weird inconsistencies, iirc).

**Comment by ChrisDenton** [comment] 2024-11-05 23:04
The quick workaround would be to use `String::from_utf8_lossy` for non-unicode output.

**Comment by NobodyXu** [comment] 2024-11-05 23:10
Yes, perhaps forwarding stdout as well is the right thing to do in cc.

It would take some extra effort though

**Comment by mingerfan** [comment] 2024-11-21 07:07
@ChrisDenton I saw the issue in Cargo. So the current best solution is to use cargo run -vv or cargo build -vv, right? Not outputting non-UTF-8 characters seems to be a feature 🤔.

**Comment by madsmtm** [comment] 2024-11-24 05:12
We could perhaps also consider setting `LC_ALL=C VSLANG=1033` to force compiler messages to be in English? `rustc` [already does this when invoking the linker](https://github.com/rust-lang/rust/blob/5db81020006d2920fc9c62ffc0f4322f90bffa04/compiler/rustc_codegen_ssa/src/back/linker.rs#L27-L38).

**Comment by NobodyXu** [comment] 2024-11-24 08:13
Thanks Mads, I think that'd be the best solution for this!

**Comment by ChrisDenton** [comment] 2024-11-24 08:33
`VSLANG=1033` may help in some situations but it won't work at all if the user doesn't have the Visual Studio English Language pack installed and it also won't fix it for paths or other user input that contains non ASCII characters. That's why I added a [function to the compiler](https://github.com/rust-lang/rust/blob/5db81020006d2920fc9c62ffc0f4322f90bffa04/compiler/rustc_codegen_ssa/src/back/link.rs#L1231) that converts to non UTF-8 output from `link.exe`.

**Comment by NobodyXu** [comment] 2024-11-24 08:37
Thanks, would it be possible to do the same for build-script stdout?

**Comment by ChrisDenton** [comment] 2024-11-24 09:12
I don't think `cargo build -vv` is a fix. More of a workaround.

A better approach for developers with admin access to their dev machines is to set the system locale to UTF-8 (note: this is only available on recent versions of Windows and is still marked as beta, though it has worked well enough for me)

<details><summary>System UTF-8</summary>

There should be a tick box in Administrative language settings that enables the UTF-8 locale.

![Image](https://github.com/user-attachments/assets/bcd63f94-8275-430b-b0cf-d80e8a441083)

</details>

Ideally I do think a) `cc` should convert non UTF-8 output and b) cargo shouldn't hide output without even a warning that it is doing so

**Comment by NobodyXu** [comment] 2024-11-24 10:00
> cc should convert non UTF-8 output

It's doable but it'd make our existing codebase a bit more complex.

It be great if it can done in cargo, but if there's no other way we can do this.

**Closed** 2024-11-26 12:58 UTC

**Comment by MeFisto94** [comment] 2025-08-03 22:34
Hey, sorry for commenting on this existing issue, but for me (german locale) I still have the issue of not being able to see compiler errors. I do get an exerpt of stderr but other than that, tI only know that the command invocation failed with exit code 1, but not the compiler errors that are printed on stdout.
My band-aid fix so far is this:
```diff
diff --git a/src/command_helpers.rs b/src/command_helpers.rs
index 32d7c71..3affc5f 100644
--- a/src/command_helpers.rs
+++ b/src/command_helpers.rs
@@ -359,7 +359,12 @@ pub(crate) fn run_output(cmd: &mut Command, cargo_output: &CargoOutput) -> Resul
         .unwrap();

     // Don't care about this output, use the normal settings
-    wait_on_child(cmd, &mut child, cargo_output)?;
+    let res = wait_on_child(cmd, &mut child, cargo_output);
+    if let Err(e) = res {
+        // If the command failed, we still return the output, but we also propagate the error.
+        eprintln!("{}", String::from_utf8_lossy(&stdout));
+        return Err(e);
+    }

     Ok(stdout)
 }
diff --git a/src/lib.rs b/src/lib.rs
index 3f0da9d..5eaff5e 100644
--- a/src/lib.rs
+++ b/src/lib.rs
@@ -1822,7 +1822,7 @@ impl Build {

         for obj in objs {
             let mut cmd = self.create_compile_object_cmd(obj)?;
-            run(&mut cmd, &self.cargo_output)?;
+            run_output(&mut cmd, &self.cargo_output)?;
         }

         Ok(())
```

Now, technically the child should be spawned with Stdout::inherited. Is there something specific to the rest of the process structure (i.e. cargo) that makes this fail? I've pondered whether this could also be a case of the child process dying too fast to flush stdout to the parent process or anything remotely connected? But then that should be the same problem when capturing the output...

I'd love to help diagnose this further, if you can tell me how.

**Comment by NobodyXu** [comment] 2025-08-04 10:07
Thanks for reporting!

In short:
 - we do forward stdout by default, unless the build script turns it off by using [`Build::cargo_output`](https://docs.rs/cc/latest/cc/struct.Build.html#method.cargo_output)
 - it does forward stderr

Edit: remove incorrect information

**Comment by NobodyXu** [comment] 2025-08-07 10:53
Ok turned out I was wrong, non parallel version does forward stderr.

Sorry about the confusion
